# Generated by Django 2.2.16 on 2021-10-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20211016_2035'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='following',
        ),
    ]
